VNR_InternShip/Models/ErrorViewModel.cs
namespace VNR_InternShip.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VNR_InternShip/Models/KhoaHocModel.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace VNR_InternShip.Models
{
    public class KhoaHocModel
    {
        [Key]
        public int Id { get; set; }
        [Column("TenKhoaHoc", TypeName = "Varchar(30)")]
        public string NameCourse { get; set; }

        public string Image { get; set; }
    }
}

VNR_InternShip/Models/MonHocModel.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VNR_InternShip.Models
{
    public class MonHocModel
    {
        [Key]
        public int Id { get; set; }
        [Column("TenMonHoc", TypeName = "nvarchar(100)")]
        public string NameTitle { get; set; }
        [Column("MoTa", TypeName = "nvarchar(100)")]
        public string Description { get; set; }
        public string ImageKH { get; set; }
    }
}

VNR_InternShip/Controllers/KhoaHocController.cs
using Microsoft.AspNetCore.Mvc;
using VNR_InternShip.Service.Interface;

namespace VNR_InternShip.Controllers
{
    public class KhoaHocController: Controller
    {
        private readonly IKhoaHocService _khoaHocService;

        public KhoaHocController(IKhoaHocService khoaHocService)
        {
            _khoaHocService = khoaHocService;
        }
        [HttpGet]
        public async Task<IActionResult> ListKhoaHoc()
        {
            var list = await _khoaHocService.GetListKhoaHoc();
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult>ListMonHoc(int idKhoahoc)
        {
            var listKH = await _khoaHocService.GetListMonHocByKhoaHoc(idKhoahoc);
            return View(listKH);
        }
    }
}

VNR_InternShip/Views/KhoaHoc/ListKhoaHoc.cshtml
@model List<VNR_InternShip.Models.KhoaHocModel>
@{
    ViewBag.Title = "Khoa Hoc";
}
<div class="container-fluid d-flex justify-content-center" style="gap:20px">
    @foreach (var course in Model)
    {
        <div class="row mt-5">
            <div class="col-sm-4">
                <div class="card">
                    <img src="~/image/@course.Image" class="card-img-top" width="100%">
                    <div class="card-body pt-0 px-0">
                        <div class="d-flex flex-row justify-content-between mb-0 px-3">
                            <p class="text-muted mt-1 mb-0">@course.NameCourse</p>

                        </div>
                        <div class="mx-3 mt-3 mb-2">
                            <a href="@Url.Action("ListMonHoc", "KhoaHoc", new { idKhoahoc = course.Id })">
                                <button type="button" class="btn btn-danger btn-block"><small>Chi tiết</small></button>
                            </a>
                            
                            </div>
                    </div>


                </div>
            </div>
        </div>
    }
    
</div>

VNR_InternShip/Views/KhoaHoc/ListMonHoc.cshtml
@model List<VNR_InternShip.Models.MonHocModel>
@{
    ViewBag.Title = "Khoa Hoc";
}
<div class="container-fluid d-flex justify-content-center" style="gap:20px">
    @foreach (var subject in Model)
    {
        <div class="row mt-5" >
            <div class="col-sm-4">
                <div class="card">
                    <img src="~/image/@subject.ImageKH" class="card-img-top" width="100%">
                    <div class="card-body pt-0 px-0">
                        <div class="d-flex flex-row justify-content-between mb-0 px-3">
                            <p class="text-muted mt-1" >@subject.NameTitle</p>
                        </div>
                        <p class="text-muted mt-1" style="margin-left:40px">@subject.Description</p>
                    </div>


                </div>
            </div>
        </div>
    }
    
</div>
<div class="container-fluid d-flex justify-content-center mt-5">
    <a href="@Url.Action("ListKhoaHoc", "KhoaHoc")">
        <button type="button" class="btn btn-primary"><small>Trở lại</small></button>
    </a>
</div>

VNR_InternShip/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="~/css/site.css" rel="stylesheet" />
    <title>Course Page</title>

</head>

<body>

    @RenderBody()
    <!-- Bootstrap JS and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>

</html>